//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardForVisit
    {
        public int Id { get; set; }
        public int Id_Customer_Card { get; set; }
        public int Id_Visit { get; set; }
    }
}
