//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Cards
    {
        public int Id { get; set; }
        public Nullable<int> Id_Injections { get; set; }
        public Nullable<int> Id_Medicine { get; set; }
        public Nullable<int> Id_Droppers { get; set; }
        public Nullable<int> Id_Operations { get; set; }
        public int ID_Host { get; set; }
        public Nullable<int> ID_Breed { get; set; }
        public int ID_Doctor { get; set; }
        public int ID_Pet { get; set; }
    }
}
