//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public string Position { get; set; }
        public string Category { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> Id_Schedule { get; set; }
    }
}
