//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interesting_Story
    {
        public int Id_Interesting_Story { get; set; }
        public string Name { get; set; }
        public string Interesting_story1 { get; set; }
    }
}
