//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_doctors
    {
        public int Id { get; set; }
        public string ID_Doctor { get; set; }
        public Nullable<System.DateTime> Days_of_the_week_Routin { get; set; }
    }
}
