//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Breeds> Breeds { get; set; }
        public virtual DbSet<CardForVisit> CardForVisit { get; set; }
        public virtual DbSet<Customer_Cards> Customer_Cards { get; set; }
        public virtual DbSet<Doctors> Doctors { get; set; }
        public virtual DbSet<Droppers> Droppers { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Hosts> Hosts { get; set; }
        public virtual DbSet<Injections> Injections { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<Operations> Operations { get; set; }
        public virtual DbSet<Pets> Pets { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Schedule_doctors> Schedule_doctors { get; set; }
        public virtual DbSet<Interesting_Story> Interesting_Story { get; set; }
        public virtual DbSet<Visits> Visits { get; set; }
    }
}
